import Providers from "@/lib/tanstack/provider";
import { cn } from "@/lib/utils";
import { GoogleOAuthProvider } from "@react-oauth/google";
import type { Metadata } from "next";
import { Google_Sans } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "swiper/css";
import "./globals.css";

const googleSansFlex = Google_Sans({
  variable: "--font-google-sans-flex",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Diengs.id | Sewa penginapan, jeep tour, wisata, & lainya",
  description: "Generated by create next app",
};

const googleClientId = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        googleSansFlex.variable,
        "font-sans",
        "font-medium",
      )}
    >
      <body className="min-h-full flex flex-col">
        <div>
          <Toaster />
        </div>

        <Providers>
          <GoogleOAuthProvider clientId={googleClientId ?? ""}>
            {children}
          </GoogleOAuthProvider>
        </Providers>
      </body>
    </html>
  );
}
